# Generated by Django 4.2.23 on 2025-06-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
        ('blog', '0003_post_updated_on'),
    ]

    operations = [
    ]
